name: Run Browser-use

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[run-test]')"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5 
      with:
        python-version: '3.11'
        cache: 'pip' # caching pip dependencies
    - run: |
        pip install -r requirements.txt
        playwright install chromium
    
    

    - name: Run browser
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}  
      run: python ./run.py || exit 1
      
    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: report-results
        path: report/result/*

    - name: Upload videos
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: report-videos
        path: report/videos_result/*